@apiEP = http://localhost:3010/api/v1/users

###post
POST {{apiEP}}/signup
Content-Type: application/json

{
      "username":"Kabi",
  "email" : "a@email.com",
  "password": "as"
}

###comment
POST {{apiEP}}/comment/:id
Content-Type: application/json

{
  "id":"67106e97bb1e331e7a9024fb",
  "comment":"user comment 1"
}